[settings]
project=/scratch3/gmantzar/pp/cats_fitter
prefit=0
save_totalwave=1
save_partialwave=1
save_potential=1
save_phaseshift=1

; epos files
[epos]
;TODO: change to my path
path=/tank1/ge34zez/input/filesCATS/Source/EposAngularDist/

; cats input folder
[cats]
path=/tank2/ga27bor/cats_data/input/filesCATS

; files for fitting pp
[pp]
potential=norfolk
;potential=bootstrap
;potential=norfolk
;potential=av18_wf
;potential=epelbaum
;potential=pp
file=output.root
input=/tank1/ge34zez/input/250220_pp/
;output=/tank2/ga27bor/cats_data/output/250220_pp/av18_eff_massfix/
;output=/tank2/ga27bor/cats_data/output/250220_pp/Norfolk_core/
;output=/tank2/ga27bor/cats_data/output/250220_pp/av18_wf_eff/
;output=/tank2/ga27bor/cats_data/output/250220_pp/Epelbaum_eff/
;output=/tank2/ga27bor/cats_data/output/250220_pp/av18_eff_l10p/
;output=/tank2/ga27bor/cats_data/output/250220_pp/av18_eff_extra2/
output=/tank2/ga27bor/cats_data/output/250220_pp/test/
;output=/tank2/ga27bor/cats_data/output/250220_pp/av18_eff_bl/
;output=/tank2/ga27bor/cats_data/output/250220_pp/Norfolk_boot_eff/

;output=/tank2/ga27bor/cats_data/output/250220_pp/Norfolk_boot_eff_800/
;output=/tank2/ga27bor/cats_data/output/250220_pp/Norfolk_boot_core/

;0000000000000000000000000000000000
;output=/tank2/ga27bor/cats_data/output/test/Epelbaum_eff/
;output=/tank2/ga27bor/cats_data/output/test/Norfolk_boot_eff/


lampars_p=/tank1/ge34zez/input/shared/Lambda_Proton.root
lampars_a=/tank1/ge34zez/input/shared/Lambda_AntiProton.root
res_matrix_path=/tank1/ge34zez/input/shared/

; files for fitting pl
[pl]
potential=pl
input=/tank1/ge34zez/input/250527_pl/
output=/tank1/ge34zez/output/250527_pl/catsfits_freebsl/
file=output_pl.root
;file=analysis_pl.root

